
import type { Project } from "@/lib/types";
import { PlaceHolderImages } from "@/lib/placeholder-images";

export const projectsData: Project[] = [
  {
    id: "proj-1",
    slug: "campus-assistant",
    title: "Campus Assistant",
    category: "app",
    description: "A comprehensive education app for university students, featuring course management, campus info, and notifications.",
    longDescription: "Campus Assistant is a multi-platform application designed to be a one-stop solution for university students. It helps them manage their academic life by providing easy access to course materials, real-time campus notifications, and essential university information.",
    keyFeatures: ["Course Management & Schedule", "Real-time Notifications", "Campus Information Hub", "Student Profile Management"],
    role: "Lead Flutter Developer",
    challenges: "The main challenge was integrating with various university data sources and ensuring real-time notification delivery across both Android and web platforms efficiently.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-1-screenshot")?.imageUrl || "https://picsum.photos/seed/campus1/800/600",
    imageHint: "education app",
    tags: ["Flutter", "Firebase", "Figma", "Android", "Web"],
    playStoreLink: "https://play.google.com/store/apps/details?id=com.sofolit.campusassistant",
    repoLink: "https://github.com/sofolitltd/campusassistant",
    liveLink: "https://campusassistant.web.app/"
  },
  {
    id: "proj-2",
    slug: "the-forge",
    title: "The Forge",
    category: "website",
    description: "A modern portfolio website for The Forge, built with Next.js and Sanity CMS, deployed on Vercel.",
    longDescription: "The Forge is a creative agency that needed a sleek, modern, and easily updatable portfolio to showcase their work. I built a dynamic website using Next.js for high performance and Sanity as a headless CMS, allowing the team to manage their project portfolio without writing any code.",
    keyFeatures: ["Dynamic Project Showcase from CMS", "Static Site Generation for Performance", "Responsive Design", "Contact Form Integration"],
    role: "Full-Stack Developer",
    challenges: "The key challenge was creating a flexible and scalable data structure in Sanity CMS that could accommodate a wide variety of project types and media, and then rendering it beautifully on the frontend.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-2-screenshot")?.imageUrl || "https://picsum.photos/seed/forge1/800/600",
    imageHint: "modern website",
    tags: ["Next.js", "Sanity CMS", "Vercel", "Portfolio"],
    liveLink: "https://theforgebd.vercel.app/",
  },
  {
    id: "proj-3",
    slug: "petelements-bd",
    title: "Petelements BD",
    category: "website",
    description: "An e-commerce website for a pet shop, built with WordPress. Features product catalog, cart, and online ordering.",
    longDescription: "Petelements BD is an online store for pet supplies. The goal was to create a user-friendly e-commerce experience for pet owners in Bangladesh. I used WordPress and WooCommerce to build a full-featured online shop, customizing the theme and plugins to meet the client's specific branding and functionality requirements.",
    keyFeatures: ["Full Product Catalog", "Shopping Cart & Checkout", "Order Management System", "Custom WordPress Theme"],
    role: "WordPress Developer",
    challenges: "Customizing WooCommerce to handle local payment gateways and delivery options was a primary challenge, requiring deep hooks into the plugin's architecture.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-3-screenshot")?.imageUrl || "https://picsum.photos/seed/pet1/800/600",
    imageHint: "pet shop",
    tags: ["WordPress", "E-commerce", "WooCommerce"],
    liveLink: "https://www.petelementsbd.com/",
  },
  {
    id: "proj-4",
    slug: "wellbeing-clinic",
    title: "Wellbeing Clinic",
    category: "app",
    description: "A mental health and wellbeing app for psychology support and clinic management. Available on web, Android, and Play Store.",
    longDescription: "Wellbeing Clinic is a platform that connects individuals with mental health professionals. The app facilitates appointment booking, session management, and provides resources for mental wellbeing. I developed the cross-platform application using Flutter, ensuring a consistent experience on both web and mobile.",
    keyFeatures: ["Appointment Booking", "Therapist Profiles & Search", "Session Management", "Resource Library"],
    role: "Lead Flutter Developer",
    challenges: "Ensuring patient data privacy and security (HIPAA compliance considerations) was paramount. This involved careful database design and implementing strict access controls in Firestore Security Rules.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-4-screenshot")?.imageUrl || "https://picsum.photos/seed/well1/800/600",
    imageHint: "health app",
    tags: ["Mental Health", "Web", "Android", "Psychology", "Flutter"],
    liveLink: "https://wellbeingclinic.web.app/",
    repoLink: "https://github.com/sofolitltd/wellbeing-clinic",
    playStoreLink: "https://play.google.com/store/apps/details?id=com.sofolit.wellbeingclinic"
  },
  {
    id: "proj-5",
    slug: "blood-finder-app",
    title: "Blood Finder App",
    category: "app",
    description: "A web application to help connect blood donors with recipients in need. Built with Flutter for cross-platform availability.",
    longDescription: "This application aims to solve the critical problem of finding blood donors in emergency situations. It allows users to register as donors, search for donors by blood type and location, and send requests. The real-time nature of Firebase was crucial for instant updates.",
    keyFeatures: ["Donor Registration & Search", "Real-time Request System", "Location-based Filtering", "User Profiles"],
    role: "Flutter Developer",
    challenges: "The most significant challenge was designing a real-time notification system that was both reliable and efficient, ensuring that urgent blood requests reached potential donors as quickly as possible.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-5-screenshot")?.imageUrl || "https://picsum.photos/seed/blood1/800/600",
    imageHint: "medical app",
    tags: ["Flutter", "Firebase", "Health"],
    liveLink: "https://bloodfinder.web.app/",
    repoLink: "https://github.com/sofolitltd/bloodfinder",
    playStoreLink: "https://play.google.com/store/apps/details?id=com.sofolit.bloodfinder",
  },
  {
    id: "proj-6",
    slug: "certificate-generator",
    title: "Certificate Generator",
    category: "app",
    description: "A Flutter application for generating and customizing professional certificates from predefined templates.",
    longDescription: "This was a tool built to automate the creation of certificates. Users can select from various templates, input data (like names and dates), and generate high-quality, printable PDF certificates. It was built as a desktop and web application using Flutter.",
    keyFeatures: ["Template Selection", "Dynamic Data Input", "PDF Generation", "Customization Options"],
    role: "Flutter Developer",
    challenges: "Working with PDF generation libraries in Flutter and ensuring consistent, high-quality output across different platforms was the main technical hurdle. I had to carefully manage layout and font embedding to get it right.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-6-screenshot")?.imageUrl || "https://picsum.photos/seed/cert1/800/600",
    imageHint: "utility tool",
    tags: ["Flutter", "Dart", "PDF"],
    repoLink: "https://github.com/sofolitltd/certificate-generator",
  },
  {
    id: "proj-7",
    slug: "priyo-banskhali",
    title: "Priyo Banskhali",
    category: "app",
    description: "A local community app for the residents of Banskhali, providing local news, events, and a business directory.",
    longDescription: "Priyo Banskhali is designed to connect the community of Banskhali upazila. It serves as a central hub for local news, announcements of upcoming events, and a directory of local businesses and services, fostering a stronger, more connected community.",
    keyFeatures: ["Local News Feed", "Event Calendar", "Business Directory", "Emergency Contacts"],
    role: "Lead Flutter Developer",
    challenges: "Aggregating and verifying local news and business information was a significant challenge, requiring a simple backend for community members to submit content for moderation.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-7-screenshot")?.imageUrl || "https://picsum.photos/seed/priyo1/800/600",
    imageHint: "community app",
    tags: ["Flutter", "Firebase", "Community", "Getx"],
    repoLink: "https://github.com/sofolitltd/priyobanskhali",
    playStoreLink: "https://play.google.com/store/apps/details?id=com.sofolit.priyobanshkhali"
  },
  {
    id: "proj-8",
    slug: "abrar-shop",
    title: "Abrar Shop",
    category: "app",
    description: "A single-vendor e-commerce Flutter application with Riverpod state management and bKash payment integration.",
    longDescription: "Abrar Shop is a full-featured single-vendor e-commerce platform built with Flutter. It provides customers with a unified and intuitive shopping experience, robust state management with Riverpod, and secure payments via bKash.",
    keyFeatures: ["Riverpod State Management", "bKash Payment Gateway", "FCM Notifications", "Product Catalog & Search", "Shopping Cart & Checkout", "Order Management"],
    role: "Flutter Developer",
    challenges: "Integrating the bKash payment gateway required careful handling of webviews and callback URLs to ensure a secure and smooth transaction flow. Managing complex UI state and async operations was effectively handled using the Riverpod state management library.",
    imageUrl: PlaceHolderImages.find((img) => img.id === "project-8-screenshot")?.imageUrl || "https://picsum.photos/seed/abrar1/800/600",
    imageHint: "ecommerce app",
    tags: ["Flutter", "E-commerce", "Firebase", "Riverpod", "bKash", "FCM"],
    repoLink: "https://github.com/sofolitltd/abrar",
    playStoreLink: "https://play.google.com/store/apps/details?id=com.sofolit.abrar"
  }
];
